version: '3.8'
name: x-services
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'x'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'x'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'x'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'x'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  redis:
    container_name: redis
    image: redis:6.2.7
    restart: always
    ports:
      - 6379:6379
    expose:
      - '6379'
    volumes:
      - cache:/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports: 
      - 8080:8080
    expose:
      - '8080'
# Names our volume
volumes:
  my-db:
  cache:
    driver: local

networks:
  default:
    name: x_default
